config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  get 'welcome/index'
  get '/archive', to: "articles#archive"
  get '/about', to: "welcome#about"
  resources :articles do
    resources :comments
  end
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]

  def index
    @articles = Article.all
  end

  def archive
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  private
    def article_params
      params.require(:article).permit(:title, :text)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  http_basic_authenticate_with name: "Mjhugtfres456rd", password: "34rghytrLO_*&Nfdrf", only: :destroy

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @articles = Article.order('created_at DESC').first(5)
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article, local: true do |form| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <div class="form-group floating-label-form-group controls">
      <%= form.label :title %>
      <%= form.text_field :title, placeholder: "Title" %>
      <p class="help-block text-danger"></p>
    </div>
  </div>

  <div class="control-group">
    <div class="form-group floating-label-form-group controls">
      <%= form.label :text %><br>
      <%= form.cktext_area :text, ckeditor: {height: "500",  language: 'pl'} %>
      <p class="help-block text-danger"></p>
    </div>
  </div>

  <p>
    <%= form.submit %>
  </p>

<% end %>

app/views/articles/archive.html.erb
<!-- Page Header -->
<header class="masthead" style="background-image: url('https://itdata.sk/wp-content/uploads/2017/12/hurbag-1100x550.jpg')">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="site-heading">
          <h1>Archive</h1>
        </div>
      </div>
    </div>
  </div>
</header>

<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
      <% @articles.each do |article| %>
      <div class="post-preview">
        <h2 class="post-title"><%= link_to article.title, article %></h2>
        <p><%= truncate(strip_tags(article.text), length: 120) { link_to "read more", article } %></p>
        <p class="post-meta">Posted by Magda on <%= article.created_at.strftime("%Y-%m-%d") %></p>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12 col-md-12 mx-auto">
      <h1>Edit article</h1>
      <%= render 'form' %>
      <%= link_to 'Back', articles_path %>
    </div>
  </div>
</div>

app/views/articles/index.html.erb
<div class="container">
  <h1>Listing Articles</h1>
  
  <%= link_to 'New article', new_article_path %>

  <table class="table table-hover">
    <thead>
      <tr>
        <th>Title</th>
        <th>Text</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= truncate(strip_tags(article.text), length: 50) %></td>
        <td><%= link_to 'Show', article_path(article) %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article_path(article),
                method: :delete,
                data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<!-- Page Header -->
    <header class="masthead" style="background-image: url('https://itdata.sk/wp-content/uploads/2017/12/hurbag-1100x550.jpg')">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="post-heading">
              <h1><%= @article.title %></h1>
              <span class="meta">Posted by Magda on <%= @article.created_at.strftime("%Y-%m-%d")%></span>
            </div>
          </div>
        </div>
      </div>
    </header>

    <!-- Post Content -->
    <article>
      <div class="container">
        <div class="row">
          <div class="col-lg-10 col-md-12 mx-auto">
            <%= raw @article.text %>
          </div>
        </div>
      </div>
    </article>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Destroy Comment', [comment.article, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_with(model: [ @article, @article.comments.build ], local: true) do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pl">

  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
      <div class="container">
        <%= link_to "Home", root_path, class: "navbar-brand" %>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <%= link_to "Archive", archive_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "About me", about_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="contact.html">Contact</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <%= yield %>

    <hr>

    <!-- Footer -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <ul class="list-inline text-center">
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fas fa-circle fa-stack-2x"></i>
                    <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fas fa-circle fa-stack-2x"></i>
                    <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fas fa-circle fa-stack-2x"></i>
                    <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>


    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

app/views/welcome/about.html.erb
<header class="masthead" style="background-image: url('https://itdata.sk/wp-content/uploads/2017/12/hurbag-1100x550.jpg')">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="site-heading">
          <h1>Co nieco o mnie :)</h1>
        </div>
      </div>
    </div>
  </div>
</header>

<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">

      <p> Strona w budowie.<br><br>
          Po informacje "o mnie" zapraszam do wpisu na stronie głównej.
      </p>
      <!---<p>
        Cześć! <br><br>

        Miło mi, że zaglądasz na moją stronę poświęconą projektom, które będę robić w trakcie kursu programowania
        webowego - <strong>CodersCamp</strong>. </p>

        <p> Coś o mnie? Jestem studentką Politechniki Wrocławskiej aktywnie interesującą się branżą IT. Oprócz działalności
           akademickiej w różnych organizacjach po godzinach rozwijam się m.in. jako IT New Business Manager w <strong>Girls in Tech
            Poland</strong> organizując meet-upy branżowe, prelekcje czy warsztaty z programowania. Na nasze eventy zapraszamy zarówn
            o firmy technologiczne, autorytety, jak i specjalistów, którzy dzielą się swoim doświadczeniem i wiedzą.
            Nasza organizacja nie tylko zwiększa zdolności technologiczne, ale i przedsiębiorczość wśród młodych kobiet
            (i nie tylko), inspiruje i mobilizuje do działania oraz rozwoju. </p>

        <p>Dodatkowo zgłębiam wiedzę techniczną z dziedziny IT - przez ostatnie pół roku szkoliłam się w zakresie testowania
           oprogramowania, a obecnie biorę udział w kursie web developmentu <strong>CodersCamp</strong> i uczę się programować.
           Poza tym, że zależy mi na ciągłym rozwoju w tym kierunku, mogę powiedzieć, że szybko przyswajam nowe technologie,
           lubię próbować nowych rzeczy i jestem pozytywną, zorganizowaną osobą, zmotywowaną do ciężkiej pracy.
      </p> --->
    </div>
  </div>
</div>

app/views/welcome/contact.html.erb
<header class="masthead" style="background-image: url('https://itdata.sk/wp-content/uploads/2017/12/hurbag-1100x550.jpg')">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="site-heading">
          <h1>Contact</h1>
        </div>
      </div>
    </div>
  </div>
</header>

<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
      <%= BetterLorem.p(5).html_safe %>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<header class="masthead" style="background-image: url('https://itdata.sk/wp-content/uploads/2017/12/hurbag-1100x550.jpg')">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="site-heading">
          <h1>Magda's Projects</h1>
        </div>
      </div>
    </div>
  </div>
</header>

<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
      <% @articles.each do |article| %>
      <div class="post-preview">
        <h2 class="post-title"><%= link_to article.title, article %></h2>
        <p><%= truncate(strip_tags(article.text), length: 120) { link_to "read more", article } %></p>
        <p class="post-meta">Posted by Magda on <%= article.created_at.strftime("%Y-%m-%d") %></p>
      <% end %>
      </div>
    </div>
  </div>
</div>